---
title: "Setup for nonlinear fitting master class"
---

1. Please make sure you have the **latest version** of R (3.6.0) installed from [CRAN](https://cran.r-project.org/).

2. The RStudio interface is strongly recommended; you can download it [here](https://www.rstudio.com/products/rstudio/download/) (get the free Desktop version).

3. Install primary fitting packages (and a variety of extras).
Note that this list deliberately takes an [everything-but-the-kitchen-sink](https://en.wiktionary.org/wiki/everything_but_the_kitchen_sink#English) approach, since it will save time to have everything you might want installed in advance. If you have questions or problems, please contact me before the workshop.

```{r pkg1,eval=FALSE}
## modeling packages
mod_pkgs <- c("alabama", "bbmle", "brms", "DEoptim", "Deriv", "dfoptim", 
              "maxLik", "minpack.lm", "minqa", "nimble", "nloptr",
              "nls2", "nlshelper", "nlstools", "nls.multstart",
              "numDeriv", "optimx", "subplex", "TMB")
## miscellaneous/data manipulation
data_pkgs <- c("benchmark", "devtools", "emdbook",
               "pkgbuild", "plyr", "reshape2", "tidyverse")
## graphics
graph_pkgs <- c("cowplot", "directlabels",
                "dotwhisker", "GGally", "ggalt", "ggplot2",
                "ggpubr", "ggstance", "gridExtra",
                "plotrix", "viridis")

all_pkgs <- c(mod_pkgs,data_pkgs,graph_pkgs)
avail_pkgs <- rownames(available.packages())
already_installed <- rownames(installed.packages())
to_install <- setdiff(all_pkgs,already_installed)
if (length(to_install)>0) {
    install.packages(to_install,dependencies=TRUE)
}
```

There is no need to (re)install packages such as `grid`, `nlme`, `MASS`, `mgcv`, as they come with a standard R installation. 

4. Various advanced tools such as TMB and Stan need compilers installed as well: 
- Windows: download Rtools from [here](https://cran.r-project.org/bin/windows/Rtools/)
- MacOS: install Xcode; on recent versions of MacOS you need to open a Terminal, type `xcode-select --install` and then click "Install" and "Agree". (If you have an older version or want more details see [here](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/); you only need to do "Step 1" of these instructions.)
- Linux: make sure you have `gcc`/`g++` installed

Also see [Checking the C++ toolchain](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started) from the Stan installation instructions. (Run `pkgbuild::has_build_tools(debug=TRUE)`.)


---
Last updated: `r Sys.time()`
